title: Jenna (Je) Yang
description: Ph.D. Candidate in Computer Science at Columbia University. Computer Architecture, Heterogeneous Reconfigurable SoC, HW/SW Co-Design.
url: https://jenna-yang.github.io
baseurl: ""
lang: en

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - Dockerfile
  - docker-compose.yaml
  - _config_docker.yml
  - package.json
  - talkmap.py
  - markdown_generator
  - scripts
  - talkmap
  - _drafts
